# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Console Calculator
# declencheur du build
on:
  push: #Quand on fait un push
    branches: [ "main" ]

permissions:
  contents: read
#Les actions qui doivent etre effectue
jobs:
  build:
    # OS
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Configuration de python
    - name: Set up Python 3.10 # La version de python souhaite
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python -m pytest test.py
